var aListContent = [
	[
		{
			title:"手机",
			url:"https://www.kuazhu.com",
			obj:[
					{
						img:"images/topnav1.webp",
						txt:"坚果 U 系列"
					},
					{
						img:"images/topnav2.webp",
						txt:"坚果 R 系列"
					}
			]
		},
		{
			title:"官方配件",
			url:"https://www.kuazhu.com",
			obj:[
					{
						img:"images/topnav3.webp",
						txt:"保护膜"
					},
					{
						img:"images/topnav4.webp",
						txt:"保护套"
					},
					{
						img:"images/topnav5.webp",
						txt:"耳机"
					},
					{
						img:"images/topnav6.webp",
						txt:"音箱"
					}
			]
		},
		{
			title:"",
			url:"https://www.kuazhu.com",
			obj:[
					{
						img:"images/topnav7.webp",
						txt:"数据线"
					},
					{
						img:"images/topnav8.webp",
						txt:"充电器"
					},
					{
						img:"images/topnav9.webp",
						txt:"自拍杆"
					},{
						img:"images/topnav10.webp",
						txt:"移动电源"
					}
			]
		},
		{
			title:"畅呼吸系列",
			url:"https://www.kuazhu.com",
			obj:[
					{
						img:"images/topnav11.webp",
						txt:"生活电器"
					},
					{
						img:"images/topnav12.webp",
						txt:"配件"
					}
			]
		},
		{
			title:"服饰箱包",
			url:"https://www.kuazhu.com",
			obj:[
					{
						img:"images/topnav13.webp",
						txt:"服装"
					},
					{
						img:"images/topnav14.webp",
						txt:"鞋子"
					}
			]
		}
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"images/topnav-1-1.webp",
			txt:"坚果 R1",
			price:"￥2999.00",
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/topnav-1-2.webp",
			txt:"坚果 R1",
			price:"￥2999.00",
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/topnav-1-3.webp",
			txt:"坚果 Pro 2S",
			price:"￥1999.00",
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/topnav-1-4.webp",
			txt:"坚果 3",
			price:"￥1899.00",
		}
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"images/topnav-2-1.webp",
			txt:"坚果 R1'足迹'系列保护套 《惊魂记》在美国首演",
			price:"￥99.00",
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/topnav-2-2.webp",
			txt:"坚果 R1'足迹'系列保护套 《惊魂记》在美国首演",
			price:"￥99.00",
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/topnav-2-3.webp",
			txt:"坚果 R1'足迹'系列保护套 《惊魂记》在美国首演",
			price:"￥99.00",
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/topnav-2-4.webp",
			txt:"坚果 R1'足迹'系列保护套 《惊魂记》在美国首演",
			price:"￥99.00",
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/topnav-2-5.webp",
			txt:"坚果 R1'足迹'系列保护套 《惊魂记》在美国首演",
			price:"￥99.00",
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/topnav-2-6.webp",
			txt:"坚果 R1'足迹'系列保护套 《惊魂记》在美国首演",
			price:"￥99.00",
		}
	],
	[
		{
			title:"保护套",
			url:"https://www.kuazhu.com",
			obj:[
					{
						img:"images/guan1.webp",
						txt:"坚果 Pro 系列保护套"
					},
					{
						img:"images/guan2.webp",
						txt:"坚果系列保护套"
					}
			]
		},
		{
			title:"保护膜",
			url:"https://www.kuazhu.com",
			obj:[
					{
						img:"images/guan3.webp",
						txt:"坚果 Pro 系列保护膜"
					},
					{
						img:"images/guan4.webp",
						txt:"坚果系列保护膜"
					}
			]
		},
		{
			title:"耳机",
			url:"https://www.kuazhu.com",
			obj:[
					{
						img:"images/guan5.webp",
						txt:"线控耳机"
					},
					{
						img:"images/guan6.webp",
						txt:"蓝牙耳机"
					}
			]
		},
		{
			title:"数据线",
			url:"https://www.kuazhu.com",
			obj:[
					{
						img:"images/guan7.webp",
						txt:"原装数据线"
					}
			]
		},
		{
			title:"充电器",
			url:"https://www.kuazhu.com",
			obj:[
					{
						img:"images/guan8.webp",
						txt:"充电器"
					}
			]
		},
		{
			title:"自拍杆",
			url:"https://www.kuazhu.com",
			obj:[
					{
						img:"images/guan9.webp",
						txt:"自拍杆"
					}
			]
		}
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"images/chang1.webp",
			txt:"畅呼吸智能落地式加湿器",
			price:"￥1999.00",
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/chang2.webp",
			txt:"畅呼吸桌面式加湿器",
			price:"￥999.00",
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/chang3.webp",
			txt:"畅呼吸智能空气净化器 · 标准版",
			price:"￥3499.00",
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/chang4.webp",
			txt:"畅呼吸智能空气净化器 · 超级除甲醛版",
			price:"￥3499.00",
		}
		,{
			url:"https://www.kuazhu.com",
			img:"images/chang5.webp",
			txt:"畅呼吸除甲醛超级活性炭滤芯",
			price:"￥699.00",
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/chang6.webp",
			txt:"畅呼吸防雾霾口罩",
			price:"￥9.90",
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/chang7.webp",
			txt:"畅呼吸除霾除甲醛高效复合滤芯",
			price:"￥799.00",
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/chang8.webp",
			txt:"畅呼吸汽车空调滤清器",
			price:"￥699.00",
		}
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"images/bao1.webp",
			txt:"地平线 8 号商务旅行箱",
			price:"￥999.00",
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/bao2.webp",
			txt:"地平线 8 号旅行箱",
			price:"￥299.00",
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/bao3.webp",
			txt:"地平线 8 号旅行箱",
			price:"￥299.00",
		}
	],
	[
		{
			title:"服饰",
			url:"https://www.kuazhu.com",
			obj:[
					{
						img:"images/pinpai1.webp",
						txt:"T恤"
					},
					{
						img:"images/pinpai2.webp",
						txt:"卫衣"
					},
					{
						img:"images/pinpai3.webp",
						txt:"衬衫"
					},
					{
						img:"images/pinpai4.webp",
						txt:"Polo衫"
					}
			]
		},
		{
			title:"鞋",
			url:"https://www.kuazhu.com",
			obj:[
					{
						img:"images/pinpai5.webp",
						txt:"帆布鞋"
					}
			]
		},
		{
			title:"文具",
			url:"https://www.kuazhu.com",
			obj:[
					{
						img:"images/pinpai6.webp",
						txt:"笔记本"
					}
			]
		},
		{
			title:"图书",
			url:"https://www.kuazhu.com",
			obj:[
					{
						img:"images/pinpai7.webp",
						txt:"图书"
					}
			]
		},
		{
			title:"家居生活",
			url:"https://www.kuazhu.com",
			obj:[
					{
						img:"images/pinpai8.webp",
						txt:"时钟"
					},
					{
						img:"images/pinpai9.webp",
						txt:"口腔护理"
					}
			]
		}
	],
];